#!/usr/bin/env bash
# Solve MathProg models with glpsol and merge into base/optim/resource_tuned.cfg
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DIR="$ROOT/tools/ampl_mathprog"
OUT="${1:-$ROOT/base/optim/resource_tuned.cfg}"
TMP1="$(mktemp)"
TMP2="$(mktemp)"
trap 'rm -f "$TMP1" "$TMP2"' EXIT

if ! command -v glpsol >/dev/null 2>&1; then
  echo "glpsol not found; install glpk-utils (Debian/Ubuntu) or use AMPL/CPLEX with these .mod files" >&2
  exit 1
fi

glpsol --math "$DIR/resource_budget.mod" -o "$TMP1" >/dev/null
dmg_step="$(awk '$2=="dmg_step"{print $4; exit}' "$TMP1")"
rec_step="$(awk '$2=="rec_step"{print $4; exit}' "$TMP1")"
if [[ -z "${dmg_step:-}" || -z "${rec_step:-}" ]]; then
  echo "failed to parse resource_budget.mod solution" >&2
  exit 1
fi

glpsol --math "$DIR/armor_balance.mod" -o "$TMP2" >/dev/null
armor_easy="$(awk '$2=="easy"{print $4; exit}' "$TMP2")"
armor_hard="$(awk '$2=="hard"{print $4; exit}' "$TMP2")"
if [[ -z "${armor_easy:-}" || -z "${armor_hard:-}" ]]; then
  echo "failed to parse armor_balance.mod solution" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
// Auto-generated by tools/ampl_mathprog/generate_resource_cfg.sh (do not hand-edit).
// Sources: tools/ampl_mathprog/resource_budget.mod, armor_balance.mod
set g_optimDmgStep $dmg_step
set g_optimRecStep $rec_step
set g_optimArmorEasy $armor_easy
set g_optimArmorHard $armor_hard
EOF

echo "Wrote $OUT (dmg=$dmg_step rec=$rec_step armor_easy=$armor_easy armor_hard=$armor_hard)"
