#!/usr/bin/env bash
# Solve resource_budget.mod with glpsol and emit base/optim/resource_tuned.cfg
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MOD="$ROOT/tools/ampl_mathprog/resource_budget.mod"
OUT="${1:-$ROOT/base/optim/resource_tuned.cfg}"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

if ! command -v glpsol >/dev/null 2>&1; then
  echo "glpsol not found; install glpk-utils (Debian/Ubuntu) or use AMPL/CPLEX with this .mod" >&2
  exit 1
fi

glpsol --math "$MOD" -o "$TMP" >/dev/null

dmg_step="$(awk '$2=="dmg_step"{print $4; exit}' "$TMP")"
rec_step="$(awk '$2=="rec_step"{print $4; exit}' "$TMP")"

if [[ -z "${dmg_step:-}" || -z "${rec_step:-}" ]]; then
  echo "failed to parse glpsol column output from $TMP" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
// Auto-generated by tools/ampl_mathprog/generate_resource_cfg.sh (do not hand-edit).
// Source: tools/ampl_mathprog/resource_budget.mod
set g_optimDmgStep $dmg_step
set g_optimRecStep $rec_step
EOF

echo "Wrote $OUT (dmg_step=$dmg_step rec_step=$rec_step)"
